language: bash
sudo: required
dist: trusty

env:
  global:
    - SHELLCHECK_VERSION=0.4.4

cache:
  directories:
    - $HOME/.cabal

install:
  - .travis/install-shellcheck.sh $SHELLCHECK_VERSION
  - .travis/install-shfmt.sh

before_script:
  - make prepare

script:
  - make test

after_success:
  - make optional
